name: Fremax Brakes Europe
favicon: null
layout_spectrum: 0.81285
typography_spectrum: 0.45455910405144095
title: Fremax Brakes Europe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffcb08'
    - '#939598'
    - '#ffff00'
    - '#ffaa00'
    - '#9f9f9f'
  brandStrength: 0.10780824860557914
  lightness: 0.01726800319738686
  saturation: 0.3798516667447984
  rhythmicContrast: 0.7669743893202394
purpose: []
